spring.application.name=pulsetrack


spring.datasource.url=jdbc:postgresql://localhost:5432/tracker_db
spring.datasource.username=postgres
spring.datasource.password=postgrespassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mvc.async.request-timeout=1800000